<x-wellcms-actions::group
    :badge="$getBadge()"
    :badge-color="$getBadgeColor()"
    dynamic-component="wellcms::icon-button"
    :group="$group"
    :label="$getLabel()"
    :size="$getSize()"
    class="re-ac-icon-btn-group"
/>
