<x-wellcms-actions::action
    :action="$action"
    :badge="$getBadge()"
    :badge-color="$getBadgeColor()"
    dynamic-component="wellcms::icon-button"
    :label="$getLabel()"
    :size="$getSize()"
    class="re-ac-icon-btn-action"
/>
